language: python
sudo: false
cache: pip
script: tox
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=docs
    - python: 3.7
      env: TOXENV=flake8
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: __token__
  password:
    secure: c36mLA+adviGP3FVp9vx82XRmbrQjPxtQ3KuuWnnIUKn1xDjf3YeVk6GRwYl4YP/zQNj9NLKJ4vN3LszZbssGd/BfYYlsPxf9MIM7FDgEe4UTtqHqdab2U5JG/8Ba/qa/btNHlqGKRcG4cxsYDxVxkat8H42yARyyWJlnQy0ies9GQS5qIhhReZxBUeRDlCSWcvxN4Vyvj9FSV+Yh+WujEMBR6pCyUyLN/O98S36O91r/VKDIi2tfSYgj7NfzL5aB4ve9o4Telurboxxtj1/OUdaJ9HNNduuNXDo4Ki4Lgf7258XuZB+zcYgIv7TBAbN/ef7r0bHpXSWDex52ZJyCAMqWhT/Kwgl8V+BnAMHLypVkGG9BJarjyCYisjYYn+5ISCestaqOacTt2WBbOT2rui0IIXTVrftNxKMNLDqV6ja9VIY31IXNg3fQBsCm/hkU0mU2/9D7+nSb1pthm1aR+muDmBGqLDpKTtL30FLJOj5y9BYZIPU9A4zKjn89Cjg8crALXrR2FCUujcEf82HocjOl2Rk64rGqs6MCnSO2xz0ltgO7YRMWtfEuHk02iZqMo9m3xZhpLeDjarEl2d0KykPnkMUwaqHf8xw+PBhhb4tdQoNkCeOUNRIL0Rhul1WT8e6ci1WFi7dzi2fxw65olGFhgVF5AGtRvVRJvDbsPs=
  on:
    branch: master
  skip_existing: true
