language: python
cache:
  - pip
  - $HOME/docker
services:
  - docker

before_cache:
  # Save tagged docker images
  # See https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
   # Load cached docker images
   - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

jobs:
  include:
    - stage: test
      name: '2.7 exmaples'
      python: 2.7
      script: python -m ifg.examples
    - name: '3.5 examples'
      python: 3.5
      script: python -m ifg.examples
    - name: '3.6 examples'
      python: 3.6
      script: python -m ifg.examples
    - name: '3.7 examples'
      python: 3.7
      script: python -m ifg.examples
    # TODO: fix python3.5 tests
    #- name: '3.5 tests'
    #  python: 3.5
    #  script: pytest
    - name: '3.6 tests'
      python: 3.6
      script: pytest
    - name: '3.7 tests'
      python: 3.7
      script: pytest
    - stage: build
      name: '2.7 build & install'
      python: 2.7
      before_script: pip install --upgrade setuptools wheel virtualenv
      script:
        - python setup.py sdist bdist_wheel
        - docker run -v $(pwd)/dist:/dist --rm python:2.7 /bin/bash -c "pip install numpy && pip install /dist/*.whl"
    - stage: build
      name: '3.5 build & install'
      python: 3.5
      before_script: pip install --upgrade setuptools wheel
      script:
        - python setup.py sdist bdist_wheel
        - docker run -v $(pwd)/dist:/dist --rm python:3.5 /bin/bash -c "pip install numpy && pip install /dist/*.whl"
    - stage: build
      name: '3.6 build & install'
      python: 3.6
      before_script: pip install --upgrade setuptools wheel
      script:
        - python setup.py sdist bdist_wheel
        - docker run -v $(pwd)/dist:/dist --rm python:3.6 /bin/bash -c "pip install numpy && pip install /dist/*.whl"
    - stage: build
      name: '3.7 build & install'
      python: 3.7
      before_script: pip install --upgrade setuptools wheel
      script:
        - python setup.py sdist bdist_wheel
        - docker run -v $(pwd)/dist:/dist --rm python:3.7 /bin/bash -c "pip install numpy && pip install /dist/*.whl"
    - stage: deploy
      name: "deploy to PyPi"
      script: skip
      deploy:
        provider: pypi
        twine_version: 1.12.1
        user: __token__
        password:
          secure: DM1F0tApae9m7G+8xFQf9szjwalhLY5fGcyPFpNMR1nQ8T2JCQRi549lUUTL2/kgWrsfHyfWklmc9gxc7bk1XkeHsHX3vhKRPAXBhG4bZAWyPJBbx81qCpZ1NRqFiwISjFkE0noceBYNd0CuJTuPvoRcOJ9fIeVtKk7SHhT/8okgJYZX8BeE+RUUy3HPRSNqQL7xNQfJIOWZ4mlhvJwOgUB66IjUKTtxdEZL4WQ47+G5YhxpcUP6QLlbbhi8J4KJsuw7XftLKhxSzw8Mh53Xq8M6b+av3S/ysNzKumrogGlPkz58pun/QHuAA8KRf7uoVarjY99yiN7wFzSmrGwtJB5kkLl9h1TkhqcSm87KllGXa0GsdUwMyEdBCM+ByA3CmgEN6tjj3YdDUm0AY66LPHMSG7OM0+T3Fuv4kIIMr33LCIVzxLJEMGXjWZu1M4Vxzw8aVwH97qnI+x+zwUzA0K/ha59v/GYMt7O2oGU+KQy0MwXn+1b17MY0756uAOLSJnblT0CcUUVaOtgENY1cPvFFIcZ4mgiG/xw7NFQNEjH2Q6Hq6xaYFMkO6Xny2le2P/T/x7qlBh9pS0ftvDGxB8mG8hiTqt/l7t4iDMU9YaztJBKnsgu90tYFh52GvM9kXzxTucOEWbPz0iliEGBPX991EG5p0Ib8Qof8Kgy0dfg=
        on:
          branch: master
        skip_existing: true
