[tool.poetry]
name = "ifg"
version = "1.2.0"
description = "Calculator of Ideal Fermi gas properties"
license = "MIT"
authors = [
    "Aleksei Kozharin <1alekseik1@gmail.com>",
    "Pavel Levashov <pasha@jiht.ru>"
]
maintainers = ["Aleksei Kozharin <1alekseik1@gmail.com>"]
readme = "README.md"
repository = "https://github.com/alekseik1/ifg-py"
documentation = "https://ifg-py.readthedocs.io/en/latest/"
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License"
]

[tool.poetry.dependencies]
python = "^2.7 || ^3.5 || ^3.6 || ^3.7 || ^3.8 || ^3.9"
numpy = [
    # numpy 1.17.0 dropped support for python 2.7
    {version = "<1.17", python = "<3.5"},
    {version = ">=1.17, <1.22", python = ">=3.5"}
]
scipy = [
    # scipy 1.3.0 dropped support for python 2.7
    {version = "<1.3", python = "<3.5"},
    {version = ">=1.3, <1.8", python = ">=3.5"}
]
fdint = "^2.0"

[tool.poetry.dev-dependencies]
# Used only for example plots
matplotlib = [
    # matplotlib 3.0 dropped support for 2.7
    {version = "^2.2", python = "<3.5"},
    {version = ">=3, <=3.4.2", python = ">=3.5"}
]
pytest = [
    # pytest 5.0 dropped support for python < 3.5
    {version = "^4", python = "<3.5"},
    {version = ">=5.2", python = ">=3.5"}
]
flake8 = "<=3.9.2"
hypothesis = [
    # hypothesis 5.0 dropped support for python 2.7
    {version = "<5", python = "<3.5"},
    {version = ">=5, <6.15", python = ">=3.5"}
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
    "ifg/metadata.py:__version__"
]
version_toml = "pyproject.toml:tool.poetry.version"
build_command = "python setup.py bdist_wheel"
