name: build and deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: build PyPi package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build package
        run: |
          python setup.py bdist_wheel
      - name: Save built package
        uses: actions/upload-artifact@v3
        with:
          name: pypi-package
          path: |
            dist/*

  deploy:
    name: deploy to PyPi
    runs-on: ubuntu-latest

    steps:
      - name: Download an artifact package
        uses: actions/download-artifact@v2
        with:
          name: pypi-package
          path: dist/
      - name: Publish distribution 📦 to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}