name: examples

on:
  push:
    # master has separate pipeline
    branches-ignore:
      - 'master'
    # docs are built externally by readthebdocs
    paths-ignore:
      - 'docs/**'
  # schedule every day at midnight
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: "plots"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: '2.7'
            poetry-version: '1.1.15'
          - python-version: '3.6'
            poetry-version: '1.1.15'
          - python-version: '3.7'
            poetry-version: '1.5.1'
          - python-version: '3.8'
            poetry-version: '1.8.3'
          - python-version: '3.9'
            poetry-version: '1.8.3'
          - python-version: '3.10'
            poetry-version: '1.8.3'
          - python-version: '3.11'
            poetry-version: '1.8.3'
          - python-version: '3.12'
            poetry-version: '1.8.3'
    container:
      image: "python:${{ matrix.python-version }}"

    steps:
      - uses: actions/checkout@v2
      - name: Install poetry
        run: pip install poetry==${{ matrix.poetry-version }}
      - name: Disable new installer for 2.7
        run: |
          if echo ${{ matrix.poetry-version }} | grep -c '2.7'
          then
            python -m poetry config experimental.new-installer false
          else
            echo 'no need to disable this feature'
          fi
        shell: bash
      - name: Install dependencies
        run: python -m poetry install
      - name: Install matplotlib
        run: poetry run python -m pip install numpy
      - name: Run examples
        run: poetry run python -m ifg.examples
